Make ubuntu-regression-suite skippable on unbootable kernels.
BugLink: https://bugs.launchpad.net/bugs/1823056
Signed-off-by: Dimitri John Ledkov <xnox@ubuntu.com>
Acked-by: Seth Forshee <seth.forshee@canonical.com>
Acked-by: Andy Whitcroft <apw@canonical.com>
Signed-off-by: Seth Forshee <seth.forshee@canonical.com>

diff --git a/debian/tests/ubuntu-regression-suite b/debian/tests/ubuntu-regression-suite
--- a/debian/tests/ubuntu-regression-suite
+++ b/debian/tests/ubuntu-regression-suite
@@ -1,6 +1,17 @@
 #!/bin/sh
 set -e
 
+# Only run regression-suite on kernels we can boot in canonistack
+source=`dpkg-parsechangelog -SSource`
+case $source in
+    linux|linux-hwe|linux-kvm|linux-oem)
+	;;
+    *)
+	echo "ubuntu-regression-suite is pointless, if one cannot boot the kernel"
+	exit 77
+	;;
+esac
+
 sver=`dpkg-parsechangelog -SVersion`
 read x rver x </proc/version_signature
 
