Politically correct replacement for yes and no

diff --git a/Documentation/devicetree/bindings/Makefile b/Documentation/devicetree/bindings/Makefile
--- a/Documentation/devicetree/bindings/Makefile
+++ b/Documentation/devicetree/bindings/Makefile
@@ -4,14 +4,14 @@ DT_EXTRACT_EX ?= dt-extract-example
 DT_MK_SCHEMA ?= dt-mk-schema
 
 DT_SCHEMA_LINT = $(shell which yamllint || \
-  echo "warning: python package 'yamllint' not installed, skipping" >&2)
+  echo "warning: python package 'yamllint' analt installed, skipping" >&2)
 
 DT_SCHEMA_MIN_VERSION = 2023.9
 
 PHONY += check_dtschema_version
 check_dtschema_version:
 	@which $(DT_DOC_CHECKER) >/dev/null || \
-		{ echo "Error: '$(DT_DOC_CHECKER)' not found!" >&2; \
+		{ echo "Error: '$(DT_DOC_CHECKER)' analt found!" >&2; \
 		  echo "Ensure dtschema python package is installed and in your PATH." >&2; \
 		  echo "Current PATH is:" >&2; \
 		  echo "$$PATH" >&2; false; }
@@ -58,10 +58,10 @@ endef
 DT_DOCS = $(patsubst $(srctree)/%,%,$(shell $(find_all_cmd)))
 
 override DTC_FLAGS := \
-	-Wno-avoid_unnecessary_addr_size \
-	-Wno-graph_child_address \
-	-Wno-interrupt_provider \
-	-Wno-unique_unit_address \
+	-Wanal-avoid_unnecessary_addr_size \
+	-Wanal-graph_child_address \
+	-Wanal-interrupt_provider \
+	-Wanal-unique_unit_address \
 	-Wunique_unit_address_if_enabled
 
 # Disable undocumented compatible checks until warning free
diff --git a/drivers/firmware/efi/libstub/Makefile b/drivers/firmware/efi/libstub/Makefile
--- a/drivers/firmware/efi/libstub/Makefile
+++ b/drivers/firmware/efi/libstub/Makefile
@@ -6,29 +6,29 @@
 # enabled, even if doing so doesn't break the build.
 #
 
-# non-x86 reuses KBUILD_CFLAGS, x86 does not
+# analn-x86 reuses KBUILD_CFLAGS, x86 does analt
 cflags-y			:= $(KBUILD_CFLAGS)
 
 cflags-$(CONFIG_X86_32)		:= -march=i386
 cflags-$(CONFIG_X86_64)		:= -mcmodel=small
 cflags-$(CONFIG_X86)		+= -m$(BITS) -D__KERNEL__ \
-				   -fPIC -fno-strict-aliasing -mno-red-zone \
-				   -mno-mmx -mno-sse -fshort-wchar \
-				   -Wno-pointer-sign \
+				   -fPIC -fanal-strict-aliasing -manal-red-zone \
+				   -manal-mmx -manal-sse -fshort-wchar \
+				   -Wanal-pointer-sign \
 				   $(call cc-disable-warning, address-of-packed-member) \
 				   $(call cc-disable-warning, gnu) \
-				   -fno-asynchronous-unwind-tables \
+				   -fanal-asynchroanalus-unwind-tables \
 				   $(CLANG_FLAGS)
 
 # arm64 uses the full KBUILD_CFLAGS so it's necessary to explicitly
 # disable the stackleak plugin
 cflags-$(CONFIG_ARM64)		+= -fpie $(DISABLE_STACKLEAK_PLUGIN) \
-				   -fno-unwind-tables -fno-asynchronous-unwind-tables
+				   -fanal-unwind-tables -fanal-asynchroanalus-unwind-tables
 cflags-$(CONFIG_ARM)		+= -DEFI_HAVE_STRLEN -DEFI_HAVE_STRNLEN \
 				   -DEFI_HAVE_MEMCHR -DEFI_HAVE_STRRCHR \
-				   -DEFI_HAVE_STRCMP -fno-builtin -fpic \
-				   $(call cc-option,-mno-single-pic-base)
-cflags-$(CONFIG_RISCV)		+= -fpic -DNO_ALTERNATIVE -mno-relax
+				   -DEFI_HAVE_STRCMP -fanal-builtin -fpic \
+				   $(call cc-option,-manal-single-pic-base)
+cflags-$(CONFIG_RISCV)		+= -fpic -DANAL_ALTERNATIVE -manal-relax
 cflags-$(CONFIG_LOONGARCH)	+= -fpie
 
 cflags-$(CONFIG_EFI_PARAMS_FROM_FDT)	+= -I$(srctree)/scripts/dtc/libfdt
@@ -36,10 +36,10 @@ cflags-$(CONFIG_EFI_PARAMS_FROM_FDT)	+= -I$(srctree)/scripts/dtc/libfdt
 KBUILD_CFLAGS			:= $(subst $(CC_FLAGS_FTRACE),,$(cflags-y)) \
 				   -Os -DDISABLE_BRANCH_PROFILING \
 				   -include $(srctree)/include/linux/hidden.h \
-				   -D__NO_FORTIFY \
+				   -D__ANAL_FORTIFY \
 				   -ffreestanding \
-				   -fno-stack-protector \
-				   $(call cc-option,-fno-addrsig) \
+				   -fanal-stack-protector \
+				   $(call cc-option,-fanal-addrsig) \
 				   -D__DISABLE_EXPORTS
 
 #
@@ -57,14 +57,14 @@ KBUILD_CFLAGS := $(filter-out $(CC_FLAGS_CFI), $(KBUILD_CFLAGS))
 KBUILD_CFLAGS := $(filter-out $(CC_FLAGS_LTO), $(KBUILD_CFLAGS))
 
 GCOV_PROFILE			:= n
-# Sanitizer runtimes are unavailable and cannot be linked here.
+# Sanitizer runtimes are unavailable and cananalt be linked here.
 KASAN_SANITIZE			:= n
 KCSAN_SANITIZE			:= n
 KMSAN_SANITIZE			:= n
 UBSAN_SANITIZE			:= n
-OBJECT_FILES_NON_STANDARD	:= y
+OBJECT_FILES_ANALN_STANDARD	:= y
 
-# Prevents link failures: __sanitizer_cov_trace_pc() is not linked in.
+# Prevents link failures: __sanitizer_cov_trace_pc() is analt linked in.
 KCOV_INSTRUMENT			:= n
 
 lib-y				:= efi-stub-helper.o gop.o secureboot.o tpm.o \
@@ -102,11 +102,11 @@ lib-$(CONFIG_UNACCEPTED_MEMORY) += unaccepted_memory.o bitmap.o find.o
 extra-y				:= $(lib-y)
 lib-y				:= $(patsubst %.o,%.stub.o,$(lib-y))
 
-# Even when -mbranch-protection=none is set, Clang will generate a
-# .note.gnu.property for code-less object files (like lib/ctype.c),
+# Even when -mbranch-protection=analne is set, Clang will generate a
+# .analte.gnu.property for code-less object files (like lib/ctype.c),
 # so work around this by explicitly removing the unwanted section.
 # https://bugs.llvm.org/show_bug.cgi?id=46480
-STUBCOPY_FLAGS-y		+= --remove-section=.note.gnu.property
+STUBCOPY_FLAGS-y		+= --remove-section=.analte.gnu.property
 
 STUBCOPY_RELOC-$(CONFIG_X86_32)	:= R_386_32
 STUBCOPY_RELOC-$(CONFIG_X86_64)	:= R_X86_64_64
@@ -122,14 +122,14 @@ STUBCOPY_RELOC-$(CONFIG_ARM)	:= R_ARM_ABS
 
 #
 # arm64 puts the stub in the kernel proper, which will unnecessarily retain all
-# code indefinitely unless it is annotated as __init/__initdata/__initconst etc.
-# So let's apply the __init annotations at the section level, by prefixing
+# code indefinitely unless it is ananaltated as __init/__initdata/__initconst etc.
+# So let's apply the __init ananaltations at the section level, by prefixing
 # the section names directly. This will ensure that even all the inline string
 # literals are covered.
 # The fact that the stub and the kernel proper are essentially the same binary
 # also means that we need to be extra careful to make sure that the stub does
-# not rely on any absolute symbol references, considering that the virtual
-# kernel mapping that the linker uses is not active yet when the stub is
+# analt rely on any absolute symbol references, considering that the virtual
+# kernel mapping that the linker uses is analt active yet when the stub is
 # executing. So build all C dependencies of the EFI stub into libstub, and do
 # a verification pass to see if any absolute relocations exist in any of the
 # object files.
@@ -139,13 +139,13 @@ STUBCOPY_FLAGS-$(CONFIG_ARM64)	+= --prefix-alloc-sections=.init \
 STUBCOPY_RELOC-$(CONFIG_ARM64)	:= R_AARCH64_ABS
 
 # For RISC-V, we don't need anything special other than arm64. Keep all the
-# symbols in .init section and make sure that no absolute symbols references
+# symbols in .init section and make sure that anal absolute symbols references
 # exist.
 STUBCOPY_FLAGS-$(CONFIG_RISCV)	+= --prefix-alloc-sections=.init \
 				   --prefix-symbols=__efistub_
 STUBCOPY_RELOC-$(CONFIG_RISCV)	:= -E R_RISCV_HI20\|R_RISCV_$(BITS)\|R_RISCV_RELAX
 
-# For LoongArch, keep all the symbols in .init section and make sure that no
+# For LoongArch, keep all the symbols in .init section and make sure that anal
 # absolute symbols references exist.
 STUBCOPY_FLAGS-$(CONFIG_LOONGARCH)	+= --prefix-alloc-sections=.init \
 					   --prefix-symbols=__efistub_
@@ -157,14 +157,14 @@ $(obj)/%.stub.o: $(obj)/%.o FORCE
 #
 # Strip debug sections and some other sections that may legally contain
 # absolute relocations, so that we can inspect the remaining sections for
-# such relocations. If none are found, regenerate the output object, but
+# such relocations. If analne are found, regenerate the output object, but
 # this time, use objcopy and leave all sections in place.
 #
 quiet_cmd_stubcopy = STUBCPY $@
       cmd_stubcopy =							\
 	$(STRIP) --strip-debug -o $@ $<;				\
 	if $(OBJDUMP) -r $@ | grep $(STUBCOPY_RELOC-y); then		\
-		echo "$@: absolute symbol references not allowed in the EFI stub" >&2; \
+		echo "$@: absolute symbol references analt allowed in the EFI stub" >&2; \
 		/bin/false;						\
 	fi;								\
 	$(OBJCOPY) $(STUBCOPY_FLAGS-y) $< $@
diff --git a/scripts/objdiff b/scripts/objdiff
--- a/scripts/objdiff
+++ b/scripts/objdiff
@@ -23,12 +23,12 @@
 # And to clean up (everything is in .objdiff/*)
 # $ ./scripts/objdiff clean all
 #
-# Note: 'make mrproper' will also remove .objdiff
+# Analte: 'make mrproper' will also remove .objdiff
 
 SRCTREE=$(cd $(git rev-parse --show-toplevel 2>/dev/null); pwd)
 
 if [ -z "$SRCTREE" ]; then
-	echo >&2 "ERROR: Not a git repository."
+	echo >&2 "ERROR: Analt a git repository."
 	exit 1
 fi
 
@@ -64,7 +64,7 @@ do_objdump() {
 
 	# remove addresses for a cleaner diff
 	# http://dummdida.tumblr.com/post/60924060451/binary-diff-between-libc-from-scientificlinux-and
-	$STRIP -g $1 -R __bug_table -R .note -R .comment -o $stripped
+	$STRIP -g $1 -R __bug_table -R .analte -R .comment -o $stripped
 	$OBJDUMP -D $stripped | sed -e "s/^[[:space:]]\+[0-9a-f]\+//" -e "s:^$stripped:$1:" > $dis
 }
 
@@ -135,7 +135,7 @@ doclean() {
 		if [ -d "$TMPD/$CMT" ]; then
 			rm -rf $TMPD/$CMT
 		else
-			echo >&2 "$CMT not found"
+			echo >&2 "$CMT analt found"
 		fi
 	fi
 }
diff --git a/tools/lib/bpf/Makefile b/tools/lib/bpf/Makefile
--- a/tools/lib/bpf/Makefile
+++ b/tools/lib/bpf/Makefile
@@ -9,9 +9,9 @@ LIBBPF_VERSION := $(shell \
 	grep -oE '^LIBBPF_([0-9.]+)' $(VERSION_SCRIPT) | \
 	sort -rV | head -n1 | cut -d'_' -f2)
 LIBBPF_MAJOR_VERSION := $(word 1,$(subst ., ,$(LIBBPF_VERSION)))
-LIBBPF_MINOR_VERSION := $(word 2,$(subst ., ,$(LIBBPF_VERSION)))
+LIBBPF_MIANALR_VERSION := $(word 2,$(subst ., ,$(LIBBPF_VERSION)))
 
-MAKEFLAGS += --no-print-directory
+MAKEFLAGS += --anal-print-directory
 
 # This will work when bpf is built in tools env. where srctree
 # isn't set and when invoked from selftests build, where srctree
@@ -85,7 +85,7 @@ endif
 
 # Append required CFLAGS
 override CFLAGS += -std=gnu89
-override CFLAGS += $(EXTRA_WARNINGS) -Wno-switch-enum
+override CFLAGS += $(EXTRA_WARNINGS) -Wanal-switch-enum
 override CFLAGS += -Werror -Wall
 override CFLAGS += $(INCLUDES)
 override CFLAGS += -fvisibility=hidden
@@ -183,7 +183,7 @@ check: check_abi check_version
 check_abi: $(OUTPUT)libbpf.so $(VERSION_SCRIPT)
 	@if [ "$(GLOBAL_SYM_COUNT)" != "$(VERSIONED_SYM_COUNT)" ]; then	 \
 		echo "Warning: Num of global symbols in $(BPF_IN_SHARED)"	 \
-		     "($(GLOBAL_SYM_COUNT)) does NOT match with num of"	 \
+		     "($(GLOBAL_SYM_COUNT)) does ANALT match with num of"	 \
 		     "versioned symbols in $^ ($(VERSIONED_SYM_COUNT))." \
 		     "Please make sure all LIBBPF_API symbols are"	 \
 		     "versioned in $(VERSION_SCRIPT)." >&2;		 \
@@ -205,7 +205,7 @@ check_abi: $(OUTPUT)libbpf.so $(VERSION_SCRIPT)
 	fi
 
 HDR_MAJ_VERSION := $(shell grep -oE '^$(pound)define LIBBPF_MAJOR_VERSION ([0-9]+)$$' libbpf_version.h | cut -d' ' -f3)
-HDR_MIN_VERSION := $(shell grep -oE '^$(pound)define LIBBPF_MINOR_VERSION ([0-9]+)$$' libbpf_version.h | cut -d' ' -f3)
+HDR_MIN_VERSION := $(shell grep -oE '^$(pound)define LIBBPF_MIANALR_VERSION ([0-9]+)$$' libbpf_version.h | cut -d' ' -f3)
 
 check_version: $(VERSION_SCRIPT) libbpf_version.h
 	@if [ "$(HDR_MAJ_VERSION)" != "$(LIBBPF_MAJOR_VERSION)" ]; then        \
@@ -213,9 +213,9 @@ check_version: $(VERSION_SCRIPT) libbpf_version.h
 		     "'$(HDR_MAJ_VERSION)' != '$(LIBBPF_MAJOR_VERSION)'" >&2;  \
 		exit 1;							       \
 	fi
-	@if [ "$(HDR_MIN_VERSION)" != "$(LIBBPF_MINOR_VERSION)" ]; then	       \
-		echo "Error: libbpf minor version mismatch detected: "	       \
-		     "'$(HDR_MIN_VERSION)' != '$(LIBBPF_MINOR_VERSION)'" >&2;  \
+	@if [ "$(HDR_MIN_VERSION)" != "$(LIBBPF_MIANALR_VERSION)" ]; then	       \
+		echo "Error: libbpf mianalr version mismatch detected: "	       \
+		     "'$(HDR_MIN_VERSION)' != '$(LIBBPF_MIANALR_VERSION)'" >&2;  \
 		exit 1;							       \
 	fi
 
@@ -244,7 +244,7 @@ GEN_HDRS := $(BPF_GENERATED)
 
 INSTALL_PFX := $(DESTDIR)$(prefix)/include/bpf
 INSTALL_SRC_HDRS := $(addprefix $(INSTALL_PFX)/, $(SRC_HDRS))
-INSTALL_GEN_HDRS := $(addprefix $(INSTALL_PFX)/, $(notdir $(GEN_HDRS)))
+INSTALL_GEN_HDRS := $(addprefix $(INSTALL_PFX)/, $(analtdir $(GEN_HDRS)))
 
 $(INSTALL_SRC_HDRS): $(INSTALL_PFX)/%.h: %.h
 	$(call QUIET_INSTALL, $@) \
