Fixed bug where 'yes' and 'no' are mixed up

diff --git a/arch/s390/scripts/Makefile.chkbss b/arch/s390/scripts/Makefile.chkbss
--- a/arch/s390/scripts/Makefile.chkbss
+++ b/arch/s390/scripts/Makefile.chkbss
@@ -12,7 +12,7 @@ chkbss: $(addprefix $(obj)/, $(chkbss-files))
 quiet_cmd_chkbss = CHKBSS  $<
       cmd_chkbss = \
 	if ! $(OBJSIZE) --common $< | $(AWK) 'END { if ($$3) exit 1 }'; then \
-		echo "error: $< .bss section is not empty" >&2; exit 1; \
+		echo "error: $< .bss section is yest empty" >&2; exit 1; \
 	fi; \
 	touch $@;
 
diff --git a/drivers/firmware/efi/libstub/Makefile b/drivers/firmware/efi/libstub/Makefile
--- a/drivers/firmware/efi/libstub/Makefile
+++ b/drivers/firmware/efi/libstub/Makefile
@@ -8,9 +8,9 @@
 cflags-$(CONFIG_X86_32)		:= -march=i386
 cflags-$(CONFIG_X86_64)		:= -mcmodel=small
 cflags-$(CONFIG_X86)		+= -m$(BITS) -D__KERNEL__ -O2 \
-				   -fPIC -fno-strict-aliasing -mno-red-zone \
-				   -mno-mmx -mno-sse -fshort-wchar \
-				   -Wno-pointer-sign \
+				   -fPIC -fyes-strict-aliasing -myes-red-zone \
+				   -myes-mmx -myes-sse -fshort-wchar \
+				   -Wyes-pointer-sign \
 				   $(call cc-disable-warning, address-of-packed-member) \
 				   $(call cc-disable-warning, gnu)
 
@@ -19,15 +19,15 @@ cflags-$(CONFIG_X86)		+= -m$(BITS) -D__KERNEL__ -O2 \
 cflags-$(CONFIG_ARM64)		:= $(subst $(CC_FLAGS_FTRACE),,$(KBUILD_CFLAGS)) \
 				   -fpie $(DISABLE_STACKLEAK_PLUGIN)
 cflags-$(CONFIG_ARM)		:= $(subst $(CC_FLAGS_FTRACE),,$(KBUILD_CFLAGS)) \
-				   -fno-builtin -fpic \
-				   $(call cc-option,-mno-single-pic-base)
+				   -fyes-builtin -fpic \
+				   $(call cc-option,-myes-single-pic-base)
 
 cflags-$(CONFIG_EFI_ARMSTUB)	+= -I$(srctree)/scripts/dtc/libfdt
 
 KBUILD_CFLAGS			:= $(cflags-y) -DDISABLE_BRANCH_PROFILING \
 				   -D__NO_FORTIFY \
 				   $(call cc-option,-ffreestanding) \
-				   $(call cc-option,-fno-stack-protector) \
+				   $(call cc-option,-fyes-stack-protector) \
 				   -D__DISABLE_EXPORTS
 
 GCOV_PROFILE			:= n
@@ -35,7 +35,7 @@ KASAN_SANITIZE			:= n
 UBSAN_SANITIZE			:= n
 OBJECT_FILES_NON_STANDARD	:= y
 
-# Prevents link failures: __sanitizer_cov_trace_pc() is not linked in.
+# Prevents link failures: __sanitizer_cov_trace_pc() is yest linked in.
 KCOV_INSTRUMENT			:= n
 
 lib-y				:= efi-stub-helper.o gop.o secureboot.o tpm.o \
@@ -58,14 +58,14 @@ CFLAGS_arm64-stub.o		:= -DTEXT_OFFSET=$(TEXT_OFFSET)
 
 #
 # arm64 puts the stub in the kernel proper, which will unnecessarily retain all
-# code indefinitely unless it is annotated as __init/__initdata/__initconst etc.
-# So let's apply the __init annotations at the section level, by prefixing
+# code indefinitely unless it is anyestated as __init/__initdata/__initconst etc.
+# So let's apply the __init anyestations at the section level, by prefixing
 # the section names directly. This will ensure that even all the inline string
 # literals are covered.
 # The fact that the stub and the kernel proper are essentially the same binary
 # also means that we need to be extra careful to make sure that the stub does
-# not rely on any absolute symbol references, considering that the virtual
-# kernel mapping that the linker uses is not active yet when the stub is
+# yest rely on any absolute symbol references, considering that the virtual
+# kernel mapping that the linker uses is yest active yet when the stub is
 # executing. So build all C dependencies of the EFI stub into libstub, and do
 # a verification pass to see if any absolute relocations exist in any of the
 # object files.
@@ -83,14 +83,14 @@ $(obj)/%.stub.o: $(obj)/%.o FORCE
 #
 # Strip debug sections and some other sections that may legally contain
 # absolute relocations, so that we can inspect the remaining sections for
-# such relocations. If none are found, regenerate the output object, but
+# such relocations. If yesne are found, regenerate the output object, but
 # this time, use objcopy and leave all sections in place.
 #
 quiet_cmd_stubcopy = STUBCPY $@
       cmd_stubcopy =							\
 	$(STRIP) --strip-debug -o $@ $<;				\
 	if $(OBJDUMP) -r $@ | grep $(STUBCOPY_RELOC-y); then		\
-		echo "$@: absolute symbol references not allowed in the EFI stub" >&2; \
+		echo "$@: absolute symbol references yest allowed in the EFI stub" >&2; \
 		/bin/false;						\
 	fi;								\
 	$(OBJCOPY) $(STUBCOPY_FLAGS-y) $< $@
diff --git a/scripts/dtc/dtx_diff b/scripts/dtc/dtx_diff
--- a/scripts/dtc/dtx_diff
+++ b/scripts/dtc/dtx_diff
@@ -19,18 +19,18 @@ Usage:
         diff DTx_1 and DTx_2
 
 
-      --annotate    synonym for -T
-      --color       synonym for -c (requires diff with --color support)
+      --anyestate    syyesnym for -T
+      --color       syyesnym for -c (requires diff with --color support)
        -c           enable colored output
        -f           print full dts in diff (--unified=99999)
-       -h           synonym for --help
-       -help        synonym for --help
+       -h           syyesnym for --help
+       -help        syyesnym for --help
       --help        print this message and exit
        -s SRCTREE   linux kernel source tree is at path SRCTREE
                         (default is current directory)
        -S           linux kernel source tree is at root of current git repo
-       -T           Annotate output .dts with input source file and line (-T -T for more details)
-       -u           unsorted, do not sort DTx
+       -T           Anyestate output .dts with input source file and line (-T -T for more details)
+       -u           unsorted, do yest sort DTx
 
 
 Each DTx is processed by the dtc compiler to produce a sorted dts source
@@ -48,7 +48,7 @@ If DTx contains the binary blob magic value in the first four bytes,
 
 Otherwise DTx is treated as a dts source file (aka .dts).
 
-   If this script is not run from the root of the linux source tree,
+   If this script is yest run from the root of the linux source tree,
    and DTx utilizes '#include' or '/include/' then the path of the
    linux source tree can be provided by '-s SRCTREE' or '-S' so that
    include paths will be set properly.
@@ -58,7 +58,7 @@ Otherwise DTx is treated as a dts source file (aka .dts).
    or '/include/' to be processed.
 
    If DTx_1 and DTx_2 are in different architectures, then this script
-   may not work since \${ARCH} is part of the include path.  Two possible
+   may yest work since \${ARCH} is part of the include path.  Two possible
    workarounds:
 
       `basename $0` \\
@@ -122,14 +122,14 @@ compile_to_dts() {
 
 		echo ""                                                      >&2
 		echo "Possible hints to resolve the above error:"            >&2
-		echo "  (hints might not fix the problem)"                   >&2
+		echo "  (hints might yest fix the problem)"                   >&2
 
 		hint_given=0
 
 		if [ "${ARCH}" = "" ] ; then
 			hint_given=1
 			echo ""                                              >&2
-			echo "  shell variable \$ARCH not set"               >&2
+			echo "  shell variable \$ARCH yest set"               >&2
 		fi
 
 		dtx_arch=`echo "/${dtx}" | sed -e 's|.*/arch/||' -e 's|/.*||'`
@@ -138,14 +138,14 @@ compile_to_dts() {
 			hint_given=1
 			echo ""                                              >&2
 			echo "  architecture ${dtx_arch} is in file path,"   >&2
-			echo "  but does not match shell variable \$ARCH"    >&2
+			echo "  but does yest match shell variable \$ARCH"    >&2
 			echo "  >>\$ARCH<< is: >>${ARCH}<<"                  >&2
 		fi
 
 		if [ ! -d ${srctree}/arch/${ARCH} ] ; then
 			hint_given=1
 			echo ""                                              >&2
-			echo "  ${srctree}/arch/${ARCH}/ does not exist"     >&2
+			echo "  ${srctree}/arch/${ARCH}/ does yest exist"     >&2
 			echo "  Is \$ARCH='${ARCH}' correct?"                >&2
 			echo "  Possible fix: use '-s' option"               >&2
 
@@ -166,7 +166,7 @@ compile_to_dts() {
 
 	else
 		echo ""                                                     >&2
-		echo "ERROR: ${dtx} does not exist or is not readable"      >&2
+		echo "ERROR: ${dtx} does yest exist or is yest readable"      >&2
 		echo ""                                                     >&2
 		exit 2
 	fi
@@ -176,7 +176,7 @@ compile_to_dts() {
 
 # -----  start of script
 
-annotate=""
+anyestate=""
 cmd_diff=0
 diff_flags="-u"
 diff_color=""
@@ -219,11 +219,11 @@ while [ $# -gt 0 ] ; do
 		shift
 		;;
 
-	-T | --annotate )
-		if [ "${annotate}"  = "" ] ; then
-			annotate="-T"
-		elif [ "${annotate}"  = "-T" ] ; then
-			annotate="-T -T"
+	-T | --anyestate )
+		if [ "${anyestate}"  = "" ] ; then
+			anyestate="-T"
+		elif [ "${anyestate}"  = "-T" ] ; then
+			anyestate="-T -T"
 		fi
 		shift
 		;;
@@ -301,15 +301,15 @@ if [ ! -x ${DTC} ] ; then
 
 ERROR: unable to find a 'dtc' program
 
-   Preferred 'dtc' (built from Linux kernel source tree) was not found or
-   is not executable.
+   Preferred 'dtc' (built from Linux kernel source tree) was yest found or
+   is yest executable.
 
       'dtc' is: ${DTC}
 
-      If it does not exist, create it from the root of the Linux source tree:
+      If it does yest exist, create it from the root of the Linux source tree:
 ${make_command}
 
-      If not at the root of the Linux kernel source tree -s SRCTREE or -S
+      If yest at the root of the Linux kernel source tree -s SRCTREE or -S
       may need to be specified to find 'dtc'.
 
       If 'O=\${dir}' is specified in your Linux builds, this script requires
@@ -319,7 +319,7 @@ ${make_command}
       If \${KBUILD_OUTPUT} is a relative path, then '-s SRCDIR', -S, or run
       this script from the root of the Linux kernel source tree is required.
 
-   Fallback '${__DTC}' was also not in \${PATH} or is not executable.
+   Fallback '${__DTC}' was also yest in \${PATH} or is yest executable.
 
 eod
 		exit 2
@@ -339,14 +339,14 @@ if (( ${cmd_diff} )) ; then
 fi
 
 cpp_flags="\
-	-nostdinc                                  \
+	-yesstdinc                                  \
 	-I${srctree}/scripts/dtc/include-prefixes  \
 	-undef -D__DTS__"
 
 DTC="\
 	${DTC}                                     \
 	-i ${srctree}/scripts/dtc/include-prefixes \
-	-O dts -qq -f ${dtc_sort} ${annotate} -o -"
+	-O dts -qq -f ${dtc_sort} ${anyestate} -o -"
 
 
 # -----  do the diff or decompile
diff --git a/tools/debugging/kernel-chktaint b/tools/debugging/kernel-chktaint
--- a/tools/debugging/kernel-chktaint
+++ b/tools/debugging/kernel-chktaint
@@ -13,7 +13,7 @@ usage: ${0##*/}
 Call without parameters to decode /proc/sys/kernel/tainted.
 
 Call with a positive integer as parameter to decode a value you
-retrieved from /proc/sys/kernel/tainted on another system.
+retrieved from /proc/sys/kernel/tainted on ayesther system.
 
 EOF
 }
@@ -25,7 +25,7 @@ if [ "$1"x != "x" ]; then
 	elif  [ $1 -ge 0 ] 2>/dev/null ; then
 		taint=$1
 	else
-		echo "Error: Parameter '$1' not a positive interger. Aborting." >&2
+		echo "Error: Parameter '$1' yest a positive interger. Aborting." >&2
 		exit 1
 	fi
 else
@@ -39,7 +39,7 @@ else
 fi
 
 if [ $taint -eq 0 ]; then
-	echo "Kernel not Tainted"
+	echo "Kernel yest Tainted"
 	exit
 else
 	echo "Kernel is \"tainted\" for the following reasons:"
