templates/block_device_drivers/test-relay-disk: Check 'insmod'/'rmmod' failure
'test-relay-disk' continues test even if 'insmod'/'rmmod' failed.  This
commit makes the test to check if those failed.

Signed-off-by: SeongJae Park <sj38.park@gmail.com>

diff --git a/tools/labs/templates/block_device_drivers/4-5-relay-disk/test-relay-disk b/tools/labs/templates/block_device_drivers/4-5-relay-disk/test-relay-disk
--- a/tools/labs/templates/block_device_drivers/4-5-relay-disk/test-relay-disk
+++ b/tools/labs/templates/block_device_drivers/4-5-relay-disk/test-relay-disk
@@ -3,8 +3,16 @@
 PHYSICAL_DISK_NAME="/dev/vdb"
 TMP_FILE="/tmp/disk_data"
 echo "abc" > "$PHYSICAL_DISK_NAME"
-insmod relay-disk.ko
-rmmod relay-disk
+if ! insmod relay-disk.ko
+then
+	echo "insmod failed"
+	exit 1
+fi
+if ! rmmod relay-disk
+then
+	echo "rmmod failed"
+	exit 1
+fi
 sleep 1
 
 echo -n "read from $PHYSICAL_DISK_NAME: "
